/** @type {import('tailwindcss').Config} */
export default {
  mode: "jit",
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        "nebula-text": "#cdd6f4",
        "nebula-accent": "#cba6f7",
        "nebula-blue": "#89b4fa",
        "mocha-rosewater": "#f5e0dc",
        "mocha-flamingo": "#f2cdcd",
        "mocha-pink": "#f5c2e7",
        "mocha-red": "#f38ba8",
        "mocha-maroon": "#eba0ac",
        "mocha-peach": "#fab387",
        "mocha-yellow": "#f9e2af",
        "mocha-green": "#a6e3a1",
        "mocha-teal": "#94e2d5",
        "mocha-sky": "#89dceb",
        "mocha-sapphire": "#74c7ec",
        "mocha-lavender": "#b4befe",
        "mocha-subtext1": "#bac2de",
        "mocha-subtext0": "#a6adc8",
        "mocha-overlay2": "#9399b2",
        "mocha-overlay1": "#7f849c",
        "mocha-overlay0": "#6c7086",
        "mocha-surface2": "#585b70",
        "mocha-surface1": "#45475a",
        "mocha-surface0": "#313244",
        "mocha-base": "#1e1e2e",
        "mocha-mantle": "#181825",
        "mocha-crust": "#11111b",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
